FRONT-END-BOOTCAMP-PLUS-3/DevMate

app/(anon)/layout.tsx, components/header/Header.module.scss, components/header/Header.tsx
=> 공통 컴포넌트 제작 - header

__tests__/components/testExam.test.tsx, package-lock.json, package.json, vite.config.ts
=> test: RTL, Vitest 설치 및 예시 추가

components/badge/badge.module.scss, components/badge/badge.tsx, styles/colors.scss
=> 공통 컴포넌트 제작 - badge

prisma/migrations/20250221065707_init/migration.sql, prisma/schema.prisma
- prisma SQL문 수정 했습니다! (enum 제거)
=> feat: prisma SQL문 수정

app/(anon)/recruitments/_components/RecruitmentsItem/RecruitmentsItem.module.scss, app/(anon)/recruitments/_components/RecruitmentsItem/RecruitmentsItem.tsx
> 상대경로를 절대경로로 변경
> 프로젝트 설명에서 줄바꿈 되면 말줌임표 생성
=> [Feature/recruitment UI]  상대경로를 절대경로로 변경, 프로젝트 설명에서 줄바꿈 되면 말줌임표 생성

__tests__/components/RecruitmentDetail/CommentContent.test.tsx, __tests__/components/RecruitmentDetail/CommentForm.test.tsx, __tests__/components/RecruitmentDetail/LikeButton.test.tsx, __tests__/components/RecruitmentDetail/RecruitmentContent.test.tsx, __tests__/components/RecruitmentDetail/RecruitmentDetail.test.tsx, app/(anon)/recruitments/[id]/_components/CommentContentList.tsx, app/(anon)/recruitments/[id]/_components/LikeButton.module.scss, app/(anon)/recruitments/[id]/_components/LikeButton.tsx, app/(anon)/recruitments/[id]/_components/RecruitmentContent.module.scss, app/(anon)/recruitments/[id]/_components/RecruitmentContent.tsx, app/(anon)/recruitments/[id]/page.tsx, domain/entities/comment.ts, domain/entities/user.ts, prisma/migrations/20250225020904_update/migration.sql, prisma/migrations/20250225061812_init/migration.sql, prisma/schema.prisma, vitest.setup.ts
- 모집글 상세 페이지 테스트 케이스 추가
- 모집글 상세 페이지 UI 구현
- prisma SQL문 수정
- **추후 백엔드 연결 예정**
<br />
=> [feature/recuitmentDetail] 모집글 상세 페이지

__tests__/components/RecruitmentDetail/RecruitmentContent.test.tsx, __tests__/components/apply/Apply.test.tsx, app/(anon)/recruitments/[id]/_components/CommentContentList.tsx, app/(anon)/recruitments/[id]/_components/RecruitmentContent.module.scss, app/(anon)/recruitments/[id]/_components/RecruitmentContent.tsx, app/(anon)/recruitments/[id]/page.tsx, app/user/recruitments/[id]/apply/Apply.module.scss, app/user/recruitments/[id]/apply/page.tsx, components/inputField/InputField.tsx, styles/globals.scss
- 지원하기 페이지 테스트 코드 추가 및 기능 구현
- 모집 상세 페이지 버튼 이벤트 테스트 및 이벤트 추가
- 공용 버튼 컴포넌트 props 수정
=> [feature/recuitmentApply] 지원하기 페이지 UI 완

app/user/recruitments/[id]/apply/Apply.module.scss, app/user/recruitments/[id]/apply/page.tsx
=> [feature/recuitmentApply] rename: 충돌 해결

application/usecases/dtos/applyDto.ts, application/usecases/dtos/commentDto.ts, application/usecases/dtos/memberDto.ts, application/usecases/dtos/noticeDto.ts, application/usecases/dtos/projectDto.ts, application/usecases/dtos/projectTagDto.ts, application/usecases/dtos/tagDto.ts, application/usecases/dtos/techStackTagDto.ts, application/usecases/dtos/userDto.ts
Resolves #44
usecase에 쓰일 기본 dto를 작성했습니다
=> [feature/usecase-basic-dto] 기본 usecase dto 생성

components/header/Header.tsx
=> [feat] 헤더에 마이페이지 경로 수정

app/(anon)/login/_actions/loginSeverAction.ts, application/usecases/auth/login/loginUsecase.ts, middleware.ts
=> fix - login 에러

__tests__/app/(anon)/recruitments/[id]/_components/commentContent.test.tsx, __tests__/app/(anon)/recruitments/[id]/_components/recruitmentContent.test.tsx, __tests__/app/user/recruitments/[id]/apply/page.test.tsx, application/usecases/recruitment/dtos/recruitmentDetailDto.ts
=> fix: 타입 오류 수정 (테스트, DTO)

app/user/information/information.module.scss, app/user/information/layout.tsx, app/user/information/page.tsx, package-lock.json
=> ui 구현 - 마이페이지 내정보

app/(anon)/page.tsx
루트 경로 이동 시, 자동으로 /recruitments 페이지로 리다이렉트
=> [feature/recruitment-main] 루트 경로 이동 시, 자동으로 /recruitments 페이지로 리다이렉트

__tests__/app/(anon)/recruitments/page.test.tsx, app/(anon)/recruitments/_components/recruitmentsFilters/recruitmentsFilters.module.scss, app/(anon)/recruitments/_components/recruitmentsFilters/recruitmentsFilters.tsx, app/(anon)/recruitments/_components/recruitmentsItem/recruitmentsItem.tsx, app/(anon)/recruitments/_components/recruitmentsSearch/recruitmentsSearch.module.scss, app/(anon)/recruitments/_components/recruitmentsSearch/recruitmentsSearch.tsx, app/(anon)/recruitments/_components/recruitmentsSortFilters/recruitmentsSortFilters.module.scss, app/(anon)/recruitments/_components/recruitmentsSortFilters/recruitmentsSortFilters.tsx, app/(anon)/recruitments/_components/recruitmentsTag/recruitmentsTag.module.scss, app/(anon)/recruitments/_components/recruitmentsTagSearch/recruitmentsTagSearch.module.scss, app/(anon)/recruitments/_components/recruitmentsTagSearch/recruitmentsTagSearch.tsx, app/(anon)/recruitments/_components/recruitmentsWriteButton/recruitmentsWriteButton.module.scss, app/(anon)/recruitments/_components/recruitmentsWriteButton/recruitmentsWriteButton.tsx, app/(anon)/recruitments/mockData.ts, app/(anon)/recruitments/page.tsx, app/(anon)/recruitments/recruitments.module.scss, package-lock.json, utils/elapsedText.ts, utils/simpleDataTimeFormat.ts
모집글 관련 기능 추가 및 수정 사항
✅ 기능 추가
- 모집글 리스트에서 클라이언트 컴포넌트 분리
- 모집글 리스트 페이지 서버 컴포넌트로 변경
- 모집글 리스트 mockData 생성 및 적용
- 모집글 정렬 필터 active 상태 관리
- 모집글 리스트에서 상세페이지로 가는 router 설정
- "모집중", "모집완료"에 따른 조건부 Badge 렌더링
- 모집글 태그 검색창에서 입력 시, 태그로 만들어지는 기능 구현
- 시간 변환 유틸 함수 생성
🔧 기능 수정 및 설정 추가
- 모집글 스타일 수정
- 글쓰기 버튼 클릭 시 글쓰기 페이지로 라우팅
- 로그인 시 필요한 패키지 설치
- 테스트 코드 파일 추가
=> [feature/recruitment] 모집글 관련 기능 추가 및 수정 사항

README.md
=> docs: README.md에 테스트 섹션 추가

.gitignore, app/(anon)/signup/_components/signupForm.module.scss, app/(anon)/signup/_components/signupForm.tsx, app/(anon)/signup/_hooks/use-signupReducer.ts, app/user/information/_hooks/use-editUserInfo.ts, app/user/information/information.module.scss, app/user/information/page.tsx, application/usecases/auth/signup/signupUsecase.ts, application/usecases/information/updateUserInfoUsecase.ts, infrastructure/repositories/psTagRepository.ts, utils/transformData.ts
- 프로필 이미지 URL을 상태에 추가하고, 관련 액션 및 리듀서 수정
- 사용자 정보 업데이트 시 프로필 이미지 저장 로직 구현
- 기본 프로필 이미지 설정 및 경로 관리
- 스타일 수정 및 새로운 컴포넌트 추가
=> feat: 프로필 이미지 업로드 및 저장 기능 추가

infrastructure/repositories/psApplyRepository.ts, infrastructure/repositories/psCommentRepository.ts, infrastructure/repositories/psLikeRepository.ts, infrastructure/repositories/psMemberRepository.ts, infrastructure/repositories/psProjectRepository.ts, infrastructure/repositories/psProjectTagRepository.ts, infrastructure/repositories/psTagRepository.ts, infrastructure/repositories/psTechStackTagRepository.ts, infrastructure/repositories/psUserRepository.ts
- repository에 prisma.disconnect 추가하여 데이터베이스 연결 관리하여 서버 터짐 방지
=> feat: repository prisma.disconnect 추가

app/(anon)/recruitments/_components/recruitmentsTagSearch/recruitmentsTagSearch.tsx, app/api/project/myPage/route.ts, application/usecases/project/getMyProjectsUsecase.ts, domain/repositories/projectRepository.ts, infrastructure/repositories/psProjectRepository.ts, utils/service/getMyProjects.ts
- 마이페이지 프로젝트 검색 백엔드 완료
- fetch 함수는 유틸(utils/service/) 폴더에 넣어놨습니다
<br />
> 사용 방법
※ "use client" 기준입니다
```js
"use client";
import { useEffect, useState } from "react";
import { decodeToken } from "@/utils/cookie";
import { getMyProjects } from "@/utils/service/getMyProjects";
import styles from "./myOpen.module.scss";
import type { RecruitmentsDto } from "@/application/usecases/recruitment/dtos/rectuitmentsDto";
import MyProjectItem from "../_components/myProjectItem/myProjectItem";
export default function Page() {
const [userId, setUserId] = useState<string>();
const [projects, setProjects] = useState<RecruitmentsDto[] | null>(null);
const [loading, setLoading] = useState(true);
useEffect(() => {
fetchUserId();
}, []);
useEffect(() …
```
=> [feature/my project server] 마이페이지 백엔드 완료

__tests__/app/(anon)/recruitments/page.test.tsx, app/user/projects/_components/myProjectItem/myProjectItem.module.scss, app/user/projects/_components/myProjectItem/myProjectItem.tsx, app/user/projects/myOpen/myOpen.module.scss, app/user/projects/myOpen/page.tsx, app/user/projects/myParticipate/myParticipate.module.scss, app/user/projects/myParticipate/page.tsx, app/user/recruitments/(my)/myApplyStatus/myApplyStatus.module.scss, app/user/recruitments/(post)/layout.module.scss, app/user/recruitments/(post)/myComment/myComment.module.scss, app/user/recruitments/(post)/myCreate/myCreate.module.scss, app/user/recruitments/(post)/myLike/myLike.module.scss
=> [feature/myProject-server] 마이페이지 프로젝트 조회 백엔드 연결

app/(anon)/recruitments/[id]/page.tsx, app/(anon)/recruitments/page.tsx, app/user/information/information.module.scss, app/user/projects/_components/myProjectItem/myProjectItem.module.scss, app/user/recruitments/(post)/_components/myRecruitmentItem/myRecruitmentItem.module.scss, infrastructure/repositories/psProjectRepository.ts
=> [Feature/my project server] 빌드 오류 수정

app/(anon)/recruitments/_components/recruitmentsItem/recruitmentsItem.tsx, app/(anon)/recruitments/page.tsx, app/user/projects/_components/myProjectItem/myProjectItem.tsx, app/user/projects/myOpen/page.tsx, app/user/projects/myParticipate/page.tsx, app/user/recruitments/(post)/myComment/page.tsx, app/user/recruitments/(post)/myCreate/page.tsx, app/user/recruitments/(post)/myLike/page.tsx, application/usecases/project/getMyProjectsUsecase.ts, application/usecases/recruitment/dtos/recruitmentsDto.ts, application/usecases/recruitment/getRecruitmentsUsecase.ts, infrastructure/repositories/psProjectRepository.ts
=> [feature/recruitmentDetail-server] 유스케이스 타입 오류 수정

app/(anon)/recruitments/_components/recruitmentsItem/recruitmentsItem.tsx, app/user/recruitments/(post)/myComment/page.tsx, app/user/recruitments/(post)/myCreate/page.tsx, app/user/recruitments/(post)/myLike/page.tsx
=> fix: handle optional values in recruitment components

app/(anon)/recruitments/[id]/_components/actionButtons.tsx, app/(anon)/recruitments/[id]/_components/commentForm.tsx, app/(anon)/recruitments/[id]/_components/recruitmentContent.tsx, app/(anon)/recruitments/_components/recruitmentsSortFilters/recruitmentsSortFilters.tsx, app/api/recruitments/[id]/apply/route.ts, app/api/recruitments/route.ts, app/user/projects/_components/myProjectItem/myProjectItem.module.scss, app/user/projects/_components/myProjectItem/myProjectItem.tsx, app/user/projects/myOpen/page.tsx, app/user/projects/myParticipate/page.tsx, app/user/recruitments/(handle)/[id]/apply/apply.module.scss, app/user/recruitments/(handle)/[id]/apply/page.tsx, app/user/recruitments/(post)/myLike/page.tsx, application/usecases/recruitment/getProjectTitleUsecase.ts, application/usecases/recruitment/getRecruitmentsUsecase.ts, components/button/button.module.scss, components/button/button.tsx, constants/recruitmentTypes.ts, domain/repositories/projectRepository.ts, infrastructure/repositories/psProjectRepository.ts
- #126
- 마이페이지, 내정보/프로젝트 조회, 모집글 상세 페이지, 지원서 작성 페이지 UI 및 기능 수정하였습니다.
=> [Refactor/boyoung] UI 및 기능 수정

app/(anon)/recruitments/[id]/_components/recruitmentContent.tsx, utils/cookie.ts
- 토큰 없을 시에 console.error -> console.log로 변경
=> feat: 토큰 없음 오류 처리 console.log로 변경
